name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 9.x
            - name: Get Version
              id: get_version
              shell: pwsh
              run: |
                  $version = Select-String -Path Erdtree_Launcher.csproj -Pattern '<AssemblyVersion>(.*?)</AssemblyVersion>' | ForEach-Object { $_.Matches.Groups[1].Value }
                  echo "Version extracted: $version"
                  echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
            - name: Build
              run: dotnet publish -r win-x64 -c Release
            - name: Move .exe
              shell: pwsh
              run: Move-Item -Path .\bin\Release\net9.0\win-x64\publish\Erdtree_Launcher.exe -Destination .\start_protected_game.exe
            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{env.version}}
                  name: Release v${{env.version}}
                  draft: false
                  prerelease: false
                  files: start_protected_game.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
